mysql:
    image: mysql
    ports:
        - "3308:3306"
    expose:
        - 3308
    environment:
        MYSQL_ROOT_PASSWORD: mysql
        MYSQL_DATABASE: smartagri
        MYSQL_USER: user
        MYSQL_PASSWORD: mysql
